# .github/workflows/dotnet-desktop.yml
# Maintainer: Jonathan Schoeman
#
# GitHub Actions workflow for building and testing the IMLoader WPF app (.NET 8, ClosedXML)
# This workflow does NOT include MSIX packaging/signing steps, as the project does not use a Windows Application Packaging Project.

name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      Solution_Name: IMLoader.sln
      # No test project yet; add here if/when available

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Uncomment and configure if/when you add unit tests
    # - name: Execute unit tests
    #   run: dotnet test

    # Packaging/signing steps are omitted for this WPF app
    # If you add a Windows Application Packaging Project, see the commented template in the original workflow

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: IMLoader Build
        path: |
          bin/${{ matrix.configuration }}/net8.0-windows/ 